name = "Kaiten"
author = "Hlynur"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c715f2865815dbc6ac9107d50a26bbf38f6399e0f3f962b918b099550ddd9331"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
