name = "Kaiten"
author = "Hlynur"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "220027b92de18a2d83c162554162c451359513bfe0b887eeba27044b5bac5082"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
