name = "Kaiten"
author = "Hlynur"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06361c4a9f41a214d5c465187f1077cd4a5f7232301a5b94f644b391c7279c40"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
